version: "3"

volumes:
  frontend-build:
  mongo-data:
  mongo-config:

services:
  
  mongo:
    container_name: mongodb
    image: mongo:5
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    command: mongod --port $MONGO_PORT
    restart: always

  api:
    container_name: rocket-api
    depends_on:
      - mongo
    build: ./api
    image: fullstackdocker/api:latest
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=$API_PORT
    restart: always

  frontend:
    container_name: frontend-build-image
    depends_on:
      - api
    build: ./frontend
    image: fullstackdocker/frontend:latest
    volumes:
      - frontend-build:/mnt
    # Copy the compiled production build to the volume
    command: sh -c "rm -rf /mnt/* && cp -a /src/build/* /mnt"

  nginx:
    container_name: nginx
    depends_on:
      - frontend
      - api
    image: nginx:1.21.6-alpine
    ports:
      - $NGINX_LISTEN_PORT:80
    volumes:
      - ./nginx:/etc/nginx/templates
      - frontend-build:/usr/share/nginx/html
    environment:
      - FRONTEND_HOST_NAME
      - API_HOST_NAME
      - API_PORT
    restart: always
