version: "3"

volumes:
  mongo-data:
  mongo-config:

services:

  mongo:
    container_name: mongodb
    image: mongo:5
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - $MONGO_PORT:$MONGO_PORT
