version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: fullstackdocker/frontend:dev-latest
    volumes:
      - ./frontend:/src
    ports:
      - 80:3000
    command: sh -c "npm install && chmod -R 777 node_modules && npm run start"